{
 "title": "storm Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "myinterval", "query": "10s,100s" }
  ]
 },
 "panels": [
  { "title": "Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "diagnostics.listens.ok.counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.listens.ok.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "got.info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.got.info.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "dial.ok",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "p99",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.ok.histogram",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.ok.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.ok.histogram",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "dial.ok sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.ok.histogram",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "other.addrs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.other.addrs.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "bytes.sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.bytes.sent.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "bytes.read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.bytes.read.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "dial.fail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "p99",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.fail.histogram",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.fail.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.fail.histogram",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "dial.fail sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.dial.fail.histogram",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dial.fail.count.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}