{
 "title": "Cluster Bench",
 "description": "plans/benchmarks",
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Cluster Information" },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": ":kube_pod_info_node_count:" }
   ]
  },
  {
   "title": "running pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  count(kube_pod_container_status_running{namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "redis clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 }, "content": "# Test results" },
  {
   "title": "time to start",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "start_time / 1000 / 1000" }
   ]
  },
  {
   "title": "Barrier Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(barrier_time_100_percent[10s])) / 1000 / 1000"
    },
    {
     "expr": "avg(rate(barrier_time_80_percent[10s])) / 1000 / 1000"
    },
    {
     "expr": "avg(rate(barrier_time_60_percent[10s])) / 1000 / 1000"
    },
    {
     "expr": "avg(rate(barrier_time_20_percent[10s])) / 1000 / 1000"
    }
   ]
  },
  {
   "title": "network initialization time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "net_init_time / 1000 / 1000" }
   ]
  }
 ]
}