{
 "title": "Example Dash",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "content": "# example_gauge\n\nwatch as data goes up and down\n\ncalculate averages, ranges, summations, or differences between different metrics\n\nObserve top or bottom performers. How does the top 10% compare to the bottom 10%?\n"
  },
  {
   "title": "count violations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(example_gauge < 1)" }
   ]
  },
  {
   "title": "messy gauge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "example_gauge" }
   ]
  },
  {
   "title": "gauge heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "example_gauge" }
   ]
  },
  {
   "title": "average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(example_gauge)" },
    { "expr": "stddev(example_gauge)" },
    { "expr": "max(example_gauge)" },
    { "expr": "stdvar(example_gauge)" }
   ]
  },
  {
   "title": "do math",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(example_gauge2[1m])) - max(example_gauge)"
    }
   ]
  },
  {
   "title": "top 3 performers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(3, example_counter)" }
   ]
  },
  {
   "title": "quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "quantile(01, example_counter2)" },
    { "expr": "quantile(.5, example_counter2)" },
    {
     "expr": "quantile(0.9, example_counter2)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "content": "# Histogram\n\nMetrics are \"observed\" to be in buckets\n\nthe bucket counts are displayed in the metric."
  },
  {
   "title": "so smooth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(holt_winters(example_counter[2m], 0.2, 0.5))"
    }
   ]
  },
  {
   "title": "bucket groupings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(example_histogram_bucket[1m])) by (TestGroupId, le))"
    }
   ]
  }
 ]
}